name: Main CICD
run-name: Running the CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  modified_microservices:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.filter.outputs.any_changed }}
      dotnet_services: ${{ steps.detect_lang.outputs.dotnet_services }}
      java_services: ${{ steps.detect_lang.outputs.java_services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed microservices
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: json
          filters: |
            any_changed:
              - 'src/**'

      - name: Extract Microservice Names
        id: extract
        run: |
          FILES_JSON='${{ steps.filter.outputs.any_changed_files }}'
          SERVICES=$(echo "$FILES_JSON" | jq -r '[.[] | capture("src/(?<service>[^/]+)/.*") | .service] | unique | join(",")')
          echo "services=$SERVICES" >> $GITHUB_ENV
        shell: bash

      - name: Detect if .NET or Java code changed
        id: detect_lang
        run: |
          DOTNET_SERVICES=""
          JAVA_SERVICES=""

          for service in $(echo $services | tr ',' ' '); do
            if find src/$service -type f \( -name "*.csproj" -o -name "*.sln" \) | grep -q .; then
              DOTNET_SERVICES+="$service,"
            fi
            if find src/$service -type f \( -name "*.java" -o -name "pom.xml" -o -name "build.gradle" \) | grep -q .; then
              JAVA_SERVICES+="$service,"
            fi
          done

          DOTNET_SERVICES=${DOTNET_SERVICES%,}
          JAVA_SERVICES=${JAVA_SERVICES%,}

          echo "dotnet_services=$DOTNET_SERVICES" >> $GITHUB_ENV
          echo "java_services=$JAVA_SERVICES" >> $GITHUB_ENV

          echo "::set-output name=dotnet_services::$DOTNET_SERVICES"
          echo "::set-output name=java_services::$JAVA_SERVICES"
        shell: bash

  build-and-push:
    needs: modified_microservices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Images
        run: |
          for service in $(echo ${{ needs.modified_microservices.outputs.changed_services }} | tr ',' ' '); do
            IMAGE_NAME="ghcr.io/${{ github.repository }}/$service:latest"
            echo "Building and pushing $IMAGE_NAME"
            docker build -t $IMAGE_NAME -f src/$service/Dockerfile src/$service
            docker push $IMAGE_NAME
          done
