name: Detect File Changes
run-name: Detecting File Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files
        id: detect_files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }})

          if [ -z "$CHANGED_FILES" ]; then
            echo "No files changed."
            exit 0
          fi

          echo "Changed Files:"
          echo "$CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Debug Show changed files
        run: | 
         echo "Changed Files: ${{ env.CHANGED_FILES }}"
