name: Building the microservice
run-name: Building the microservice

on:
 push:
  branches: 
    - main
 pull_request:
  branches:
    - main

jobs:
  Detect_microservice:
    runs-on: ubuntu-latest
    outputs: 
      changed_service: "None" 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Modifies files
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
               src:
                - 'src/**'
      - name: Print changed files
        run: |
          if [[ "${{ steps.changes.outputs.src }}" == "true" ]]; then
            git diff --name-only HEAD^ HEAD | grep '^src/' || echo "No src files changed"
          else
            echo "No changes detected in src/"
          fi

