name: Building the microservice
run-name: Building the microservice

on:
 push:
  branches: 
    - main
 pull_request:
  branches:
    - main

jobs:
  Detect_microservice:
    runs-on: ubuntu-latest
    outputs: 
      changed_service: "None" 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: detect the microservice folder
        uses: dorny/paths-filter@v3
           id: detection
           with: 
            filters:
              src:
                - 'src/**'
