name: Detect File Changes
run-name: Detecting File Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }})

          if [ -z "$CHANGED_FILES" ]; then
            echo "No files changed."
            exit 0
          fi

          echo "Changed Files:"
          echo "$CHANGED_FILES"

      - name: Debug: Show changed files
        run: echo "Changed Files: $CHANGED_FILES"
        env:
          CHANGED_FILES: ${{ steps.detect_files.outputs.changed_files }}
