name: Main cicd 
run-name: Running the CICD 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  modified_microservices:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed microservices
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: json  # Enables listing changed files
          filters: |
            any_changed:
              - 'src/**'

      - name: Debug changed files
        run: |
          echo "Changed files: ${{ steps.filter.outputs.any_changed_files }}"
        shell: bash

      - name: Extract Microservice Names
        id: extract
        run: |
          FILES_JSON='${{ steps.filter.outputs.any_changed_files }}'
          SERVICES=$(echo "$FILES_JSON" | jq -r '[.[] | capture("src/(?<service>[^/]+)/.*") | .service] | unique | join(",")')
          echo "Detected services: $SERVICES"
          echo "services=$SERVICES" >> $GITHUB_ENV
        shell: bash
