run: Main cicd 
run-name: Running the CICD 

on:
 push:
  branches:
   - main
 pull_request:
   branches:
    - main

jobs:
  modified_microservies:
    runs-on: ubuntu-latest
    outputs:
      changed_Services: ${{ steps.filter.outputs.any_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  Detect the changed microservice
        id: filter
        uses: dorny/paths-filter@v2
        with:
         filters: |
           any_changed:
              - 'src/**'
