name: CodeQL Analysis

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: '0 3 * * 1' # Runs every Monday at 03:00 UTC

jobs:
  CodeQL-Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Adjust based on your project

      - name: Restore dependencies
        run: dotnet restore src/accounting/Accounting.sln # Change to your actual .sln file

      - name: Build .NET solution
        run: dotnet build src/accounting/Accounting.sln --configuration Release --no-restore

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'csharp, java' # Use 'csharp' for .NET code

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
